# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fb97761f31e18eab41aab5fb0807a3d352cdc7a69de830e660e56c308cb9ad73242a574256b6d591564a50bb173b3d0116dbb08e99de82984bf3817ddf0192f

test:
  secret_key_base: 7a6b3b2a93c1deb0228c92ae135e43fd5cb69afd21b2a5c9649d5fc61a20e08c23eabfae649f626a346f4c3ab8c7e948e083ceeb1c686bc920f8260a6b8d9c45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
